### ISSUE TITLE
[TSError] I can't run a project.

### ISSUE THREAD

**Issue by yesworld** [m-nathani/BitPoint#2]
```
/node-typescript-starter$ yarn run watch
yarn run v1.13.0
$ nodemon --watch 'src/**/*' -e ts,tsx --exec ts-node src/index.ts
[nodemon] 1.18.10
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: src/**/*
[nodemon] starting `ts-node src/index.ts`

/web/node-typescript-starter/node_modules/ts-node/src/index.ts:307
        throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
              ^
TSError: ⨯ Unable to compile TypeScript
src/index.ts (19,13): Argument of type 'Middleware<ParameterizedContext<any, {}>>' is not assignable to parameter of type 'Middleware<Context>'.
  Types of parameters 'context' and 'context' are incompatible.
    Type 'Context' is not assignable to type 'ParameterizedContext<any, {}>'.
      Type 'Context' is not assignable to type '{ app: Application<any, {}>; request: Request; response: Response; req: IncomingMessage; res: Ser...'.
        Types of property 'app' are incompatible.
          Type 'Application' is not assignable to type 'Application<any, {}>'.
            Types of property 'middleware' are incompatible.
              Type 'Middleware<Context>[]' is not assignable to type 'Middleware<ParameterizedContext<any, {}>>[]'.
                Type 'Middleware<Context>' is not assignable to type 'Middleware<ParameterizedContext<any, {}>>'.
                  Types of parameters 'context' and 'context' are incompatible.
                    Type 'ParameterizedContext<any, {}>' is not assignable to type 'Context'.
                      Types of property 'app' are incompatible.
                        Type 'Application<any, {}>' is not assignable to type 'Application'.
                          Types of property 'middleware' are incompatible.
                            Type 'Middleware<ParameterizedContext<any, {}>>[]' is not assignable to type 'Middleware<Context>[]'.
                              Type 'Middleware<ParameterizedContext<any, {}>>' is not assignable to type 'Middleware<Context>'.
                                Types of parameters 'context' and 'context' are incompatible.
                                  Type 'Context' is not assignable to type 'ParameterizedContext<any, {}>'.
                                    Type 'Context' is not assignable to type '{ app: Application<any, {}>; request: Request; response: Response; req: IncomingMessage; res: Ser...'. (2345)
src/index.ts (22,13): Argument of type 'Middleware<ParameterizedContext<any, {}>>' is not assignable to parameter of type 'Middleware<Context>'. (2345)
src/index.ts (34,13): Argument of type 'Middleware<ParameterizedContext<any, IRouterParamContext<any, {}>>>' is not assignable to parameter of type 'Middleware<Context>'.
  Types of parameters 'context' and 'context' are incompatible.
    Type 'Context' is not assignable to type 'ParameterizedContext<any, IRouterParamContext<any, {}>>'.
      Type 'Context' is not assignable to type '{ app: Application<any, {}>; request: Request; response: Response; req: IncomingMessage; res: Ser...'.
        Types of property 'app' are incompatible.
          Type 'Application' is not assignable to type 'Application<any, {}>'. (2345)
    at getOutput (/web/node-typescript-starter/node_modules/ts-node/src/index.ts:307:15)
    at /web/node-typescript-starter/node_modules/ts-node/src/index.ts:336:16
    at Object.compile (/web/node-typescript-starter/node_modules/ts-node/src/index.ts:498:11)
    at Module.m._compile (/web/node-typescript-starter/node_modules/ts-node/src/index.ts:392:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/web/node-typescript-starter/node_modules/ts-node/src/index.ts:395:12)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
[nodemon] app crashed - waiting for file changes before starting...

```

**Comment by m-nathani** [comment]
hi @yesworld, there is no yarn setup-ed in the project, please go through the [Readme](https://github.com/m-nathani/node-typescript-starter/blob/master/README.md) , and run `npm run watch` .

**Comment by m-nathani** [comment]
I cloned the project and ran the application and its working. so closing the issue.
